### ISSUE TITLE
Golang fork

### ISSUE THREAD

**Issue by juev** [ValdikSS/tor-relay-scanner#10]
Hello!

Thank you for your job!
Just for your information, I created golang fork tor-relay-scanner:
- [juev/tor-relay-scanner-go](https://github.com/juev/tor-relay-scanner-go)

Maybe it will be interesting for you?

**Comment by MistFenix** [comment]
Is it possible to add ipv6 vanilla?

**Comment by juev** [comment]
What do you mean?

This scanner checks only those relays that are presented in the list. I haven’t seen clean IPv6 relays yet.

If the IPv6 address is listed, it will be checked and displayed in the results. It is also possible to display only IPv4 results as a result.

If necessary, you can start an issue in the repository if you need to display only IPv6 results. Let’s add.

**Comment by MistFenix** [comment]
> What do you mean?
> 
> This scanner checks only those relays that are presented in the list. I haven’t seen clean IPv6 relays yet.
> 
> If the IPv6 address is listed, it will be checked and displayed in the results. It is also possible to display only IPv4 results as a result.
> 
> If necessary, you can start an issue in the repository if you need to display only IPv6 results. Let’s add.

Maybe you did not, but I see and it can get 3 ipv6 per time but need scanner for that like this to get clear results

**Comment by juev** [comment]
I added new ipv6 argument for getting only ipv6 results:
[v0.0.4](https://github.com/juev/tor-relay-scanner-go/releases/tag/v0.0.4)

The only thing I think is that if you have questions about the fork, it's better to ask them in the fork.

**Comment by MistFenix** [comment]
> I added new ipv6 argument for getting only ipv6 results:
> [v0.0.4](https://github.com/juev/tor-relay-scanner-go/releases/tag/v0.0.4)
> 
> The only thing I think is that if you have questions about the fork, it's better to ask them in the fork.

I think you have problems with this forks, I asked you both who can add, but next time I will ask only Vandik than you, thanks

**Comment by ValdikSS** [comment]
Nice! Does it any significant difference?

**Comment by juev** [comment]
tor-relay-scanner-go was created without support for integration with the Tor browser. Otherwise, I tried to reproduce the same functionality as in tor-relay-scanner.

**Comment by ValdikSS** [comment]
So it's for programming practice? Nice, but not much use for me.
