### ISSUE TITLE
--preferred-country == 1 страна.

### ISSUE THREAD

**Issue by LeonMskRu** [ValdikSS/tor-relay-scanner#14]
Example: se,gb,nl,de
запустил
tor-relay-scanner-1.0.0.exe --proxy 127.0.0.1:3128 -c nl,fi,se,no -n 4 -g 44 --timeout 15 --torrc -o bridges.conf
получил все ноды из NL
до этого были флаги fi,se,no выдавало только FI

список СТРАН. особенно с примером когда их больше одной.
ожидаются ноды из всех перечисленных стран. а не только первой указанной при запуске программы.

**Comment by ValdikSS** [comment]
Леон, вы формулируете ваши сообщения так, что я не могу их понять. Напишите подробней, что не так, и как должно быть, понятным языком, с примерами.

**Comment by LeonMskRu** [comment]
опять же проблема не только в этом.
а что оно еще и выдает их "пачками".
![TorControlPanel_FktgKrKdRE](https://github.com/ValdikSS/tor-relay-scanner/assets/67465011/3873b54f-e172-4417-9767-8765184d1bb9)

**Comment by ValdikSS** [comment]
В вашем примере `-c nl,fi,se,no` сначала происходит проверка всех релеев Нидерландов, только потом других стран по очереди, если все ноды Нидерландов недоступны.

**Comment by vgdh** [comment]
эх, последнее время из всего списка находит лишь 2-3 достпных моста в лучшем случае. 
Периодически вобще все мосты не работают, видимо в СОРМ подключили списки мостов с гита.

**Comment by LeonMskRu** [comment]
@vgdh к сожалению пока помогает только IPv6
у меня днем насканило 40+ нод IPv6 и ни одной IPv4

**Comment by vgdh** [comment]
> да еще и автор "проблем" не видит. что выдаются 10 нод из одной не то что страны. а одной /24 или вообще на одном IP но с разными портами и я понимаю что питон может не самый "удобный" в этом плане язык но уж если задали СПИСОК стран тупо сделать аналог grep -E (ru|dk|fi|etc) а не перебирать их по ОДНОЙ чтобы хоть какое то разообразие было или если можно заранее делать sort --random или как то так. чтобы не были все ноды в одном "месте"

это же opensource, можете сделать пул реквест с изменениями поведения логики ПО.

**Comment by ValdikSS** [comment]
> да еще и автор "проблем" не видит.

Эта функция работает так, как работает, намеренно. Когда я её реализовывал, мне нужно было именно это поведение — страна за страной. Это не проблема.
