### ISSUE TITLE
off-by-one error in main_async()

### ISSUE THREAD

**Issue by wildekat** [ValdikSS/tor-relay-scanner#16]
Пожалуйста, посмотрите на этот фрагмент. Здесь не надо вычитать 1:
```python
relaynum = min(NUM_RELAYS, len(relays) - relaypos - 1)
```
В следующей строке `relaynum` используется так:
```python
test_relays = [TorRelay(relays[x])
	       for x in range(relaypos, relaypos+relaynum)]
```
И `range` послушно выдаёт ровно `relaynum` значений — от `relaypos` до `relaypos+relaynum-1` включительно.
Например, при `relaypos = 8` и `len = 9` получаем неправильный `relaynum = 0` и по определению пустой `range(8, 8)`.
Таким образом, последний элемент массива `relays` теряется.

___

Мне кажется, в этой строчке логичнее использовать `relaynum` вместо `NUM_RELAYS`:
```python
print(f"\nTry {ntry}/{numtries}, We'll test the following {NUM_RELAYS} random relays:", file=sys.stderr)
```
И `{ntry+1}/{numtries}`, а то оно начинает с "Try 0/2" и заканчивает "Try 1/2". Инициализация `ntry = 0` перед циклом не нужна, её можно удалить.

___

Ещё важный момент. Вот это часто даёт неправильный результат:
```python
numtries = round(len(relays) / NUM_RELAYS)
```
Например, `round(10/4) == 2`. Протестирует 4*2 == 8 элементов, а про два последних забудет. Тут можно использовать `math.ceil`, но лучше — один из [более надёжных приёмов](https://stackoverflow.com/questions/14822184/is-there-a-ceiling-equivalent-of-operator-in-python/54585138#54585138).

___

А вот здесь квадратные скобки можно удалить за ненадобностью:
```python
return "\n".join([prefix + r for r in list_])
```

___

Опечатка: constrains -> constraints

Извините, что так много всего. Надеюсь на понимание.
Большое спасибо за программу.

**Comment by wildekat** [comment]
Предлагаю упростить цикл `for ntry in range(numtries)`:
```python
def chunked_list(l, size):
    for i in range(0, len(l), size):
        yield l[i:i+size]


for ntry, chunk in enumerate(chunked_list(relays, NUM_RELAYS)):
    relaynum = len(chunk)
    test_relays = [TorRelay(r) for r in chunk]
    ...
```
Массив аккуратно делится на кусочки, хвосты размером меньше `NUM_RELAYS` учитываются автоматически, `relaypos` исчезает сам собой и ошибиться тут просто негде. И можно будет удалить за ненадобностью некоторые другие части цикла, например:
```python
    if not test_relays:
	break
```

**Comment by plimut** [comment]
Фиркните плиз, если не затруднит, интересно посмотреть в работе.
`working_relays = list()
    ntry = 0
    relaypos = 0
    numtries = round(len(relays) / NUM_RELAYS)
....
    def chunked_list(l, size):                                      
    for i in range(0, len(l), size):
        yield l[i:i+size]
....
    for ntry, chunk in enumerate(chunked_list(relays, NUM_RELAYS)):
        relaynum = len(chunk)
        test_relays = [TorRelay(r) for r in chunk]
        relaypos += NUM_RELAYS

        print(
            f"\nTry {ntry}/{numtries}, We'll test the following {NUM_RELAYS} random relays:", file=sys.stderr)
        for relay in test_relays:
            print(relay, file=sys.stderr)
        print("", file=sys.stderr)`

Не уверен что правильно.

**Comment by wildekat** [comment]
Исправил всё перечисленное в первом посте, немного потестировал - работает как надо. [Пробуйте](https://github.com/wildekat/tor-relay-scanner)

**Comment by plimut** [comment]
Собрал torparse.pyz с доработкой wildekat, работает норм, хорошая оптимизация.

**Comment by ValdikSS** [comment]
Merged
