### ISSUE TITLE
relay scanner currently shares only IPv6 realys

### ISSUE THREAD

**Issue by 13Nina** [ValdikSS/tor-relay-scanner#18]
Hi!
https://torscan-ru.ntc.party/ only shares relays with PIv6 addresses

**Comment by ValdikSS** [comment]
There's no IPv4 relays reachable.

**Comment by 13Nina** [comment]
> There's no IPv4 relays reachable.

In Russia or overall? As I use the servise not from Russia

**Comment by ValdikSS** [comment]
torscan-**ru**.ntc.party

**Comment by LeonMskRu** [comment]
all (?) IPv6 tor relays have IPv4.
and not access from RU not mean not working

try use IPv6 bridge with torrc options
ClientUseIPv4 1
ClientUseIPv6 1
ClientPreferIPv6ORPort 0

example
Bridge [2a0e:97c0:ac0:b00b:b00b:b00b:2b13:47d8]:992 AE331A0153934DE9B7F68A19A4A89F4E979BB3A0

Jul 24 14:51:03.000 [notice] Bridge 'IKissedAGirl3' has both an IPv4 and an IPv6 address.  Will prefer using its IPv4 address (82.152.54.195:992) based on ClientPreferIPv6ORPort.
Jul 24 14:51:03.000 [notice] new bridge descriptor 'IKissedAGirl3' (fresh): $AE331A0153934DE9B7F68A19A4A89F4E979BB3A0~IKissedAGirl3 [lI7nQbSl2razacWpU46Xb8oBHf63QDk4VmrWHhZFBRc] at 82.152.54.195 and [2a0e:97c0:ac0:b00b:b00b:b00b:2b13:47d8]

https://metrics.torproject.org/rs.html#details/AE331A0153934DE9B7F68A19A4A89F4E979BB3A0
