### ISSUE TITLE
Module requests

### ISSUE THREAD

**Issue by HELLRAiSER555** [ValdikSS/tor-relay-scanner#19]
`import requests`
`with requests.get(url, timeout=int(self.timeout), proxies=self.proxy) as r:`
Where module requests?

**Comment by ValdikSS** [comment]
https://pypi.org/project/requests/

Sep 11, 2024 10:12:56 HELLRAiSER555 ***@***.***>:

**Comment by HELLRAiSER555** [comment]
I understand. Thank you. I remade it on vb.net for myself. I tried to figure it out.
