### ISSUE TITLE
Не выводится ошибка No relays are reachable, at all.

### ISSUE THREAD

**Issue by badboy322** [ValdikSS/tor-relay-scanner#4]
Проверил на двух разных компах и провайдерах. В случае, если не находит ни одного рабочего моста, скрипт обрывается и не выводит ошибку.
![image](https://user-images.githubusercontent.com/101801830/158986652-bbbec47d-5385-4a53-87e8-295dd224985d.png)

**Comment by ValdikSS** [comment]
Список релеев, которые вы видите, и есть рабочие релеи. У вас нашлось их несколько десятков.

**Comment by badboy322** [comment]
На другом провайдере, после поиска, вывод отличается. Просто странным показалось, что цикл в конце кода не исполнился в случае из скрина в ОП посте.
![image](https://user-images.githubusercontent.com/101801830/158988560-f5799c4f-6c17-486e-84f2-b8ee08d5b712.png)

**Comment by ValdikSS** [comment]
Вроде бы так и должно быть, и даже не вижу каких-либо ошибок, связанных с выводом в stderr/stdout. Похоже, бага нет.
