### ISSUE TITLE
Not available 

### ISSUE THREAD

**Issue by Pantyhose-X** [ValdikSS/tor-relay-scanner#5]
Our country Russia, China, blocked https://onionoo.torproject.org https://bridges.torproject.org/
Testing tor-relay-scanner with a proxy makes no sense at all.
You need to store the onionoo.torproject.org data crawler at raw.githubusercontent.com

**Comment by ValdikSS** [comment]
Embedded CORS proxies are used for onionoo data, and `--proxy` as well is used only for that. No proxies are used for relay availability check.
