### ISSUE TITLE
tor relay scanner doesn't work with system socks5 proxy enabled for Windows

### ISSUE THREAD

**Issue by d3vv** [ValdikSS/tor-relay-scanner#7]
OS: Windows 11

![Screenshot 2022-05-20 224920](https://user-images.githubusercontent.com/32866346/169601164-763268c7-41d5-4ca2-9125-2b587c124bb5.png)

```
tor-relay-scanner-0.0.7.exe -g 1 --timeout 3 --browser --start-browser
Tor Relay Scanner. Will scan up to 1 working relays (or till the end)
Downloading Tor Relay information from onionoo.torproject.org…
Can't download Tor Relay data from/via onionoo.torproject.org: HTTPSConnectionPool(host='onionoo.torproject.org', port=443): Max retries exceeded with url: /details?type=relay&running=true&fields=fingerprint,or_addresses (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
Can't download Tor Relay data from/via corsbypasser.herokuapp.com: HTTPSConnectionPool(host='corsbypasser.herokuapp.com', port=443): Max retries exceeded with url: /https://onionoo.torproject.org/details?type=relay&running=true&fields=fingerprint,or_addresses (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
Can't download Tor Relay data from/via corsanywhere.herokuapp.com: HTTPSConnectionPool(host='corsanywhere.herokuapp.com', port=443): Max retries exceeded with url: /https://onionoo.torproject.org/details?type=relay&running=true&fields=fingerprint,or_addresses (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
Can't download Tor Relay data from/via tauron.herokuapp.com: HTTPSConnectionPool(host='tauron.herokuapp.com', port=443): Max retries exceeded with url: /https://onionoo.torproject.org/details?type=relay&running=true&fields=fingerprint,or_addresses (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
Can't download Tor Relay data from/via cors-anywhere2.herokuapp.com: HTTPSConnectionPool(host='cors-anywhere2.herokuapp.com', port=443): Max retries exceeded with url: /https://onionoo.torproject.org/details?type=relay&running=true&fields=fingerprint,or_addresses (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
Can't download Tor Relay data from/via icors.vercel.app: HTTPSConnectionPool(host='icors.vercel.app', port=443): Max retries exceeded with url: /?https%3A//onionoo.torproject.org/details%3Ftype%3Drelay%26running%3Dtrue%26fields%3Dfingerprint%2Cor_addresses (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))
Tor Relay information can't be downloaded!
```

**Comment by ValdikSS** [comment]
How do you configure the proxy?
Just tried it on Windows 10 (not 11) by configuring Socks proxy only in "Advanced" proxy dialog in Internet Explorer, and Tor Relay Scanner doesn't use it automatically. Works fine with `--proxy` option.

**Comment by d3vv** [comment]
For example:

![proxy](https://user-images.githubusercontent.com/32866346/169659927-13432c90-629b-4743-9cb2-2d781775b125.png)

I have tried the following software for 192.168.1.7 (Linux):

1. 3proxy [ https://3proxy.ru/ ]
2. dante [ https://www.inet.no/dante/ ]

And it works for browsers and various software as well.

Also I have tried local socks5 service (at 127.0.0.1:1080) as a client for shadowsocks external server [ https://shadowsocks.org/en/ ]
All software works fine with it except tor-relay-scanner..

**Comment by ValdikSS** [comment]
The dialog on your screenshot is for HTTP proxy configuration (HTTP/CONNECT protocol). It does not support SOCKS.
Just tried to configure proxy in this dialog on Windows 10 with 3proxy socks on the server side and sure enough it did not work in any browser, because 3proxy expects SOCKS, not HTTP.
It could be something has changed in Windows 11, but I very doubt that Windows 11 implemented protocol detection and tries HTTP and SOCKS protocols on the same port, as your screenshot does not show any option for protocol selection and I have not found anything similar on the internet.

Thus, I'd guess your system does have additional proxy configuration which is apparently working somehow. Could it be you have software like proxyfier?

**Comment by d3vv** [comment]
I don't have any like proxifier or something like Layered Service Provider modifications.. Please be advised that all I did it is just enable global proxy settings for whole system here:

![proxy2](https://user-images.githubusercontent.com/32866346/169661226-6c4d173a-5ee0-4b9e-b225-30f0531f28e1.jpg)

I am not forcing the tor-relay-scanner to use this proxy.. In my case, it breaks itself when this option is enabled..

**Comment by ValdikSS** [comment]
This option supports only HTTP (CONNECT) proxies. In the OP you said you use SOCKS proxy.

With HTTP proxy, I managed to reproduce the bug. The request is executed to the proxy, but without any proxy protocol at all. WIll look.

**Comment by ValdikSS** [comment]
https://github.com/psf/requests/issues/6139

**Comment by d3vv** [comment]
@ValdikSS  okey-dockey, maybe I just wrong for something, but have no issues using sosks5 into windows 11 as global settings at work.. At home I tried http-only proxies too like squid, oops and result was the same..

**Comment by ValdikSS** [comment]
I fixed (or workarounded) the issue [in requests](https://github.com/psf/requests/pull/6162), the exe file has been rebuilt with this update. The version is still the same. Could you try and check if it's working for you?

**Comment by d3vv** [comment]
Yes, it works! Thank You in Advanced

**Comment by ValdikSS** [comment]
Yes, but only to download the list of relays, not to scan them.
