### ISSUE TITLE
Scanner for obfs4

### ISSUE THREAD

**Issue by MansurFenix** [ValdikSS/tor-relay-scanner#9]
Привет друг, а можешь сделать или добавить опцию для obfs4 мостов пожалуйста.
Я работаю на твоем скрипте и оно находит только vanilla мосты и они у нас не работает по крайнем мере.
Это было бы круто если бы сканер начал искать рабочие мосты obfs4.
Спасибо большое за работу

**Comment by vgdh** [comment]
> Привет друг, а можешь сделать или добавить опцию для obfs4 мостов пожалуйста.
> Я работаю на твоем скрипте и оно находит только vanilla мосты и они у нас не работает по крайнем мере.
> Это было бы круто если бы сканер начал искать рабочие мосты obfs4.
> Спасибо большое за работу

а есть где взять актуальный список obsf4 для проверки? 🤔

**Comment by MansurFenix** [comment]
> > Привет друг, а можешь сделать или добавить опцию для obfs4 мостов пожалуйста.
> > Я работаю на твоем скрипте и оно находит только vanilla мосты и они у нас не работает по крайнем мере.
> > Это было бы круто если бы сканер начал искать рабочие мосты obfs4.
> > Спасибо большое за работу
> 
> а где взять актуальный список obsf4 для проверки? 🤔

У меня есть готовый список

**Comment by LeonMskRu** [comment]
https://gitlab.torproject.org/gabi-250/arti-sample-project/-/tree/review-obfs4-checker/crates/obfs4-checker
